services:
# we define two separate postgres containers for development; in production we will instead use RDS and real S3 buckets
  postgres-airflow:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres-airflow-data:/var/lib/postgresql/data
    networks:
      - ml-network

  postgres-pipeline:
    image: postgres:15
    environment:
      POSTGRES_USER: mlpipeline
      POSTGRES_PASSWORD: mlpipeline
      POSTGRES_DB: mlpipeline
    ports:
      - "5433:5432"
    volumes:
      - postgres-pipeline-data:/var/lib/postgresql/data
    networks:
      - ml-network

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - ml-network

  airflow-webserver:
    build:
      context: .
      dockerfile: docker/airflow/Dockerfile
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AWS_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_REGION: eu-west-1
      S3_BUCKET_RAW: ml-pipeline-raw
      S3_BUCKET_SILVER: ml-pipeline-silver
      POSTGRES_HOST: postgres-pipeline
      POSTGRES_PORT: 5432
      POSTGRES_DB: mlpipeline
      POSTGRES_USER: mlpipeline
      POSTGRES_PASSWORD: mlpipeline
      OPENSKY_CLIENT_ID: ${OPENSKY_CLIENT_ID}
      OPENSKY_CLIENT_SECRET: ${OPENSKY_CLIENT_SECRET}
      MLFLOW_TRACKING_URI: http://mlflow:5000
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./dbt:/opt/airflow/dbt
      - airflow-logs:/opt/airflow/logs
    depends_on:
      - postgres-airflow
    networks:
      - ml-network
    command: webserver

  airflow-scheduler:
    build:
      context: .
      dockerfile: docker/airflow/Dockerfile
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AWS_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_REGION: eu-west-1
      S3_BUCKET_RAW: ml-pipeline-raw
      S3_BUCKET_SILVER: ml-pipeline-silver
      POSTGRES_HOST: postgres-pipeline
      POSTGRES_PORT: 5432
      POSTGRES_DB: mlpipeline
      POSTGRES_USER: mlpipeline
      POSTGRES_PASSWORD: mlpipeline
      OPENSKY_CLIENT_ID: ${OPENSKY_CLIENT_ID}
      OPENSKY_CLIENT_SECRET: ${OPENSKY_CLIENT_SECRET}
      MLFLOW_TRACKING_URI: http://mlflow:5000

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - airflow-logs:/opt/airflow/logs
      - ./dbt:/opt/airflow/dbt
    depends_on:
      - postgres-airflow
    networks:
      - ml-network
    command: scheduler

  airflow-init:
    build:
      context: .
      dockerfile: docker/airflow/Dockerfile
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
    depends_on:
      - postgres-airflow
    networks:
      - ml-network
    command: >
      bash -c "airflow db migrate && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"

    restart: "no"
  
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.0.0
    ports:
      - "5000:5000"
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
    command: bash -c "pip install psycopg2-binary boto3 --quiet && mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri postgresql://mlpipeline:mlpipeline@postgres-pipeline/mlpipeline --default-artifact-root s3://ml-pipeline-mlflow/"
    depends_on:
      - postgres-pipeline
      - minio
    networks:
      - ml-network

volumes:
  postgres-airflow-data:
  postgres-pipeline-data:
  minio-data:
  airflow-logs:

networks:
  ml-network:
    driver: bridge