name: Daily Pipeline

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements-api.txt

        - name: Cache MLflow models
        uses: actions/cache@v4
        with:
            path: ~/.mlflow/cache
            key: mlflow-models-${{ hashFiles('src/config.py') }}

      - name: Run pipeline
        env:
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
          WAQI_API_KEY: ${{ secrets.WAQI_API_KEY }}
          WAQI_BASE_URL: https://api.waqi.info
          WEATHER_URL: https://archive-api.open-meteo.com/v1/archive
        run: python src/pipeline/pipeline.py
